### ISSUE TITLE
Tracking issues Cudos v1.2.0

### ISSUE THREAD

**Issue by nghuyenthevinh2000** [CudoVentures/cudos-node#112]
This is tracking issue for Cudos v1.2.0

1. Remove 3 modules (addrbook, marketplace, nft)

- [x] #103 

2. Refactor the testing libraries, expanding canonical cosmos testing

- [x] https://github.com/CudoVentures/cudos-node/issues/110 (81ae6330f1412105b4b45bfe2ed2a2b0d70eec34)
- [x] https://github.com/CudoVentures/cudos-node/issues/106 (ce19cd3b1e9f9de00c07057f784ae9051293be9d)
- [x] write unit test for new logic in antehandler(d2dbcf24bcc5f1a8299564fe56b38c5d95060587)
- [x] write integration test for new logic in antehandler (81ae6330f1412105b4b45bfe2ed2a2b0d70eec34)

3. Remove modified cosmos - sdk and use canonical v0.45.16(#104)

- [x] Remove x/group  d003897412aa6ad4a2096a8b1b4a88a23bffc95d
- [x]     Adding MsgCreateValidator checker 02a24e440f4f58eb083d323489814fb450cb22ce
- [x]     Adding cudosAdmin crisis checker 633a083c5d04582a66d273a6765e3b407f18b369
- [x]     Adding custom bank module 365b7888d7304df573dec9a032b792189889ad83
- [x]     Upgrading go version + remove custom SDK bc483e1a23b262ec10823cc64d4468193eda6ae7
- [x] #118 

4. Prepare for mainnet upgrade of Cudos v1.2.0(69ea281999bba1258e6eba9be3b8abf319374601)
- [x] add upgrade handler 
- [x] add local node and upgrade test script 
5. Proto script
 
- [x] https://github.com/CudoVentures/cudos-node/pull/115

**Comment by catconcat** [comment]
#123 merged, issue is done
